BotToken: OTA0MjcyNTk2OTE1MzM1MTc5.GxlUCO.H38VI0-1-sbG3USvGl2qRYDsEYVHZjg-FElOKk
SpeakersTokens:
- MTI1MDc2MzM0NjcxNDY5MzYzMg.GgRGXF.eeDVEwwMt6JzZlmdy7K4mVowJqI_0_Bvyycaa0
- MTIyNzIwMDIxNTk3OTc4NjM3MQ.G9sLmC.E3-399wqSFk3I0GcSbSPRXjrqsSQVfGSpQA9TY
TestGuildId: 1250768227542241450
