BotToken: MTI1MDc2MzM0NjcxNDY5MzYzMg.GgRGXF.eeDVEwwMt6JzZlmdy7K4mVowJqI_0_Bvyycaa0
Speaker1Token: MTIyNzIwMDIxNTk3OTc4NjM3MQ.G9sLmC.E3-399wqSFk3I0GcSbSPRXjrqsSQVfGSpQA9TY
TestGuildId: 1250768227542241450
